// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD99N9VJq21xXAA9grbm8qKONyV8Ara6LM',
    appId: '1:628120438123:web:b898887f84e3c61b0e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    authDomain: 'rentit-11660.firebaseapp.com',
    storageBucket: 'rentit-11660.appspot.com',
    measurementId: 'G-QGKKTKTJ85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fQ582rs5uaN9sON8aYgBc9jraCD5WAY',
    appId: '1:628120438123:android:d6aabc066d8f0e4f0e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    storageBucket: 'rentit-11660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAga4ikF-SOWWBAtSq52xXVdTr5UdGjamo',
    appId: '1:628120438123:ios:cf04b17b968de0090e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    storageBucket: 'rentit-11660.appspot.com',
    iosClientId: '628120438123-hj12v707qrr8tb0op28v48cbmhbfub3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAga4ikF-SOWWBAtSq52xXVdTr5UdGjamo',
    appId: '1:628120438123:ios:cf04b17b968de0090e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    storageBucket: 'rentit-11660.appspot.com',
    iosClientId: '628120438123-hj12v707qrr8tb0op28v48cbmhbfub3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD99N9VJq21xXAA9grbm8qKONyV8Ara6LM',
    appId: '1:628120438123:web:c226e9165f927e000e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    authDomain: 'rentit-11660.firebaseapp.com',
    storageBucket: 'rentit-11660.appspot.com',
    measurementId: 'G-E75M6J3NYZ',
  );

}